name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rakibtweets/rakibtweets@main
        with:
          max_post_count: '4'
          remove_duplicates: true
          feed_list: 'https://dev.to/feed/rakibtweets'
